### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdout' of null

### ISSUE THREAD

**Issue by lilelr** [lloiser/gdb-debug#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.0
**System**: Mac OS X 10.10.5
**Thrown From**: [gdb-debug](https://github.com/lloiser/gdb-debug) package, v0.0.3
### Stack Trace

Uncaught TypeError: Cannot read property 'stdout' of null

```
At /Users/yuxiao/.atom/packages/gdb-debug/lib/gdb.js:570

TypeError: Cannot read property 'stdout' of null
    at Socket.fn (/Users/yuxiao/.atom/packages/gdb-debug/lib/gdb.js:570:15)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```
### Commands

```
     -4:26.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -2:54.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:53.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:30.4.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "linter-pylama"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-terminal, v0.8.0 (inactive)
autocomplete-clang, v0.9.3 (active)
autocomplete-python, v1.8.4 (active)
clang-format, v1.25.0 (active)
dash, v1.6.0 (inactive)
file-icons, v1.7.7 (active)
gdb-debug, v0.0.3 (active)
git-checkout, v0.2.0 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
go-config, v1.1.4 (active)
go-debug, v0.1.18 (active)
go-get, v1.0.3 (active)
go-hyperclick, v1.1.0 (active)
gometalinter-linter, v1.1.0 (active)
hyperclick, v0.0.37 (active)
linter, v1.11.14 (active)
linter-gcc, v0.6.15 (active)
linter-less, v2.6.0 (active)
linter-pylama, v0.5.6 (inactive)
linter-python, v3.0.5 (active)
linter-python-pep8, v0.2.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-writer, v2.3.3 (inactive)
merge-conflicts, v1.4.1 (inactive)
minimap, v4.24.7 (inactive)
navigator-godef, v1.0.3 (active)
path-hyperclick, v0.3.0 (active)
python-autopep8, v0.1.3 (active)
python-debugger, v0.1.0 (inactive)
python-import-magic, v0.4.0 (active)
python-tools, v0.6.8 (active)
script, v3.8.3 (inactive)
seti-ui, v0.9.2 (inactive)
switch-header-source, v0.20.0 (inactive)
symbols-tree-view, v0.12.0 (active)
terminal-plus, v0.14.5 (active)
tester-go, v1.0.4 (active)
vim-mode, v0.65.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (active)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lloiser** [comment]
I think gdb crashed... please open the developer tools in atom (`cmd alt i` or `Toggle Dev Tools` in command palette) and check if there are any errors in the console tab while you use the debugger.
Please also add a sample code to reproduce this issue.
